=== Anandhi2211/Law-Office/src/main/resources/lawfirmjaxb.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:complexType name="associationBarIdListType">
        <xs:sequence>
            <xs:element name="associationBarId" type="xs:int" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="attorneyType">
        <xs:sequence>
            <xs:element name="attorneyName" type="xs:string"/>
            <xs:element name="country" type="xs:string"/>
            <xs:element name="city" type="xs:string"/>
            <xs:element name="associationBarIdList" type="associationBarIdListType"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:int"/>
    </xs:complexType>

    <xs:complexType name="attorneyListType">
        <xs:sequence>
            <xs:element name="attorney" type="attorneyType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="awardType" >
        <xs:sequence>
            <xs:element name="awardName" type="xs:string" />
        </xs:sequence>
        <xs:attribute name="id" type="xs:int"/>
    </xs:complexType>
    
    <xs:complexType name="awardListType">
        <xs:sequence>
            <xs:element name="award" type="awardType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="lawfirmType">
        <xs:sequence>
            <xs:element name="lawFirmId" type="xs:int"/>
            <xs:element name="lawFirmName" type="xs:string"/>
            <xs:element name="address" type="xs:string"/>
            <xs:element name="country" type="xs:string"/>
            <xs:element name="city" type="xs:string"/>
            <xs:element name="awardList" type="awardListType"/>
            <xs:element name="attorneyList" type="attorneyListType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="lawfirm" type="lawfirmType">
    </xs:element>

</xs:schema>

=== Anandhi2211/Law-Office/src/main/resources/jaxb/lawfirmjaxb.xml
<?xml version="1.0" encoding="UTF-8"?>


<lawfirm xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="lawfirmjaxb.xsd">

    <lawFirmId>106</lawFirmId>
    <lawFirmName>Norris Persinger</lawFirmName>
    <address>153 Glen Street</address>
    <country>USA</country>
    <city>Washington</city>
    <awardList>
        <award id ="6">
            <awardName>Keane Award</awardName>
        </award>
        <award id ="5">
            <awardName>Smith Award</awardName>
        </award>
    </awardList>
    <attorneyList>
        <attorney id ="1012">
            <attorneyName>Vishnu</attorneyName>
            <country>USA</country>
            <city>cincinnati</city>
            <associationBarIdList>
                <associationBarId>110</associationBarId>
                <associationBarId>115</associationBarId>
                <associationBarId>106</associationBarId>
            </associationBarIdList>
        </attorney>
        <attorney id ="1013">
            <attorneyName>Kadhir</attorneyName>
            <country>USA</country>
            <city>Charlotte</city>
            <associationBarIdList>
                <associationBarId>109</associationBarId>
                <associationBarId>100</associationBarId>
                <associationBarId>106</associationBarId>
            </associationBarIdList>
        </attorney>
        <attorney id ="1014">
            <attorneyName>Kumar</attorneyName>
            <country>USA</country>
            <city>Concord</city>
            <associationBarIdList>
                <associationBarId>111</associationBarId>
                <associationBarId>106</associationBarId>
                <associationBarId>103</associationBarId>
            </associationBarIdList>
        </attorney>
    </attorneyList>
</lawfirm>
